language: python
python:
  - "3.6"
services:
  - docker

before_install:
  - docker build -t challenge-flask .
  - docker run -d --name app challenge-flask -e POSTGRES_URL=postgres -e POSTGRES_USER=rvivanco -e POSTGRES_PASS=pass1234 -e POSTGRES_DB=challengedb
script:
  - docker exec app pytest

after_script:
- docker logs app
- docker rm -f app