language: python
python:
  - "3.6"
services:
  - docker

before_install:
  - docker build -t challenge-flask .
  - docker run -d --name app challenge-flask
script:
  - docker exec app pytest
  
after_script:
- docker rm -f app