language: python
python:
  - "3.6"
services:
  - docker

before_install:
  - docker build -t flask-demo-app .
  - docker-compose up -d --force-recreate --build

before_script: pip install docker-compose

script:
  - pytest
