language: python
python:
  - "3.6"
services:
  - docker

before_install:
  - pip install docker-compose
before_script: 
  - docker-compose up app -d --force-recreate --build
script:
  - docker exec challenge_app_1 pytest
