version: '3.1'
services:
  postgres:    
    restart: always    
    image: postgres:10
    environment:      
      - POSTGRES_USER=rvivanco
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=chalengedb
    ports:
      - "5432:5432"
  app:
    build: .    
    ports:      
      - "5000:5000"
    environment:      
      - POSTGRES_URL=postgres
      - POSTGRES_USER=rvivanco
      - POSTGRES_PASS=pass1234
      - POSTGRES_DB=chalengedb
    volumes:      
      - ./app:/app
    depends_on: 
      - postgres
